### ISSUE TITLE
Cannot batch tensors with different shapes in component 0

### ISSUE THREAD

**Issue by ManoaNosea** [hieubkset/Keras-Image-Super-Resolution#8]
```F:\Keras-Image-Super-Resolution-master
λ python pretrain.py --arc=esrgan --train=F:\dod --train-ext=.png --valid=F:\dod --valid-ext=.png --cuda=1
** Loading training images
Finish loading images in 0.11s
Epoch 1/20
Traceback (most recent call last):
  File "pretrain.py", line 147, in <module>
    main()
  File "pretrain.py", line 143, in main
    train(**params)
  File "pretrain.py", line 88, in train
    validation_steps=n_val_data)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1348, in fit
    validation_steps=validation_steps)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 194, in fit_loop
    outs = f(ins)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\backend.py", line 2897, in __call__
    fetched = self._callable_fn(*array_vals)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\client\session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [128,128,3] and element 1 had shape [64,128,3].
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?,?,3], [?,?,?,3]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

**Comment by hieubkset** [comment]
Hi!
The error means the input images are not same size.
So I think you did not preprocess images by using MATLAB script.
You should follow  **Dataset** part in README.

**Comment by hieubkset** [comment]
Dataset
I use DIV2K dataset (link) which consists of 800 HR training images and 100 HR validation images. To expand the volume of training data, I applied data augmentation method as SRFeat. The author provides augmentation code. You can find it here.

Actually, DIV2K dataset only contains high resolution images (HR images) and does not contains low resolution images (LR images). So to run the code, you have to generate LR images first. You can do it by using matlab scripts (https://github.com/hieubkset/Keras-Image-Super-Resolution/tree/master/data_preprocess).

For training LR images, there are two scripts:

aug_data_div2k.m: generate LR images by using bicubic interpolation with scale 4.
aug_data_div2k_half.m: generate LR images by using bicubic interpolation with scale 2.
If you run both scripts, you shold see about 150 thousands of images for each folder (GT and LR_bicubic).

For testing LR images, using the script testset_bicubic_downsample.m

These scripts will search all HR images from a HR folder, and then generate LR images to a LR folder. So you need to modify first lines of these scripts to your HR and LR folder.
